name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API Tests
        env:
          BOOKER_USERNAME: ${{ secrets.BOOKER_USERNAME }}
          BOOKER_PASSWORD: ${{ secrets.BOOKER_PASSWORD }}
        run: |
          newman run collections/Restful_Booker_API_Tests.postman_collection.json \
            -e environments/Restful_Booker_Env.postman_environment.json \
            --env-var "base_url=https://restful-booker.herokuapp.com" \
            --env-var "username=$BOOKER_USERNAME" \
            --env-var "password=$BOOKER_PASSWORD" \
            -r htmlextra --reporter-htmlextra-export reports/api_test_report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: API Test Report
          path: reports/api_test_report.html
